# Generated by Django 2.1.5 on 2019-10-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(related_name='game', through='game.PlayerGameInfo', to='game.Player'),
        ),
    ]
